```{r setup}
library(ggplot2)
library(MOFA2)
```


```{r}
model <- load_model("../results/MOFA_3omic.hdf5")
```

```{r}
p <- plot_variance_explained(model, x="factor", y="view",)
p + ggtitle("MOFA factors with explained variation") + theme(axis.text.x = element_text(color="black", angle=40, vjust=1, hjust=1), text=element_text(family="Helvetica"), plot.title = element_text(family="Helvetica", size=18))
# ggsave("../../plots/drug/Fig4S-E_MOFA1.pdf", dpi=500)
```


```{r fig.height=8}
plot_factor(model, 
  factor = 1:3
)
```


```{r}
plot_data_heatmap(model,
  view = "protein",         # view of interest
  factor = 1,             # factor of interest
  features = 20,          # number of features to plot (they are selected by loading)
  
  # extra arguments that are passed to the `pheatmap` function
  cluster_rows = FALSE, cluster_cols = FALSE,
  show_rownames = TRUE, show_colnames = TRUE
)
```

```{r}
head(model@expectations$W$drug[order(-abs(model@expectations$W$drug[,"Factor2"])),], 30)
write.table(model@expectations$W$drug[order(-abs(model@expectations$W$drug[,"Factor2"])),], "../../data/MOFA/mofa_drugs.csv", sep = ",")
```


```{r}
head(model@expectations$W$CNV[order(-abs(model@expectations$W$CNV[,"Factor1"])),"Factor1"], 20)
head(model@expectations$W$RNA[order(-abs(model@expectations$W$RNA[,"Factor1"])),"Factor1"], 20)
head(model@expectations$W$protein[order(-abs(model@expectations$W$protein[,"Factor1"])),"Factor1"], 20)
```

```{r}
d_cnv = as.data.frame(model@expectations$W$CNV[,"Factor1"])
colnames(d_cnv) = "Factor1"
d_cnv$symbol = rownames(d_cnv)

d_rna = as.data.frame(model@expectations$W$RNA[,"Factor1"])
colnames(d_rna) = "Factor1"
d_rna$symbol = rownames(d_rna)

d_protein = as.data.frame(model@expectations$W$protein[,"Factor1"])
colnames(d_protein) = "Factor1"
d_protein$symbol = rownames(d_protein)

write.table(d_cnv, "../data/MOFA/CNV_factor1.csv", sep=",", row.names = F)
write.table(d_rna, "../data/MOFA/RNA_factor1.csv", sep=",", row.names = F)
write.table(d_protein, "../data/MOFA/protein_factor1.csv", sep=",", row.names = F)

```


```{r fig.height=6}
p = plot_weights(model,
  view = "CNV",
  factor = 1,
  nfeatures = 8,     # Number of features to highlight
  scale = T           # Scale loadings from -1 to 1
)
p + ggtitle("MOFA factor 2 top proteins") + theme(text=element_text(family="Helvetica"), plot.title = element_text(family="Helvetica", size=18))
# ggsave("../../plots/Fig4S-E_MOFA2.pdf", dpi=500)
```

```{r fig.height=6}
p = plot_weights(model,
  view = "protein",
  factor = 2,
  nfeatures = 8,     # Number of features to highlight
  scale = T           # Scale loadings from -1 to 1
)
p + theme(text=element_text(family="Helvetica")) + ggtitle("Top proteins for factor 2")
ggsave("../../plots/drug/Fig4S-E_MOFA2.pdf", dpi=500)
```